name: Android CI build
on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 设置变量
      - name: Set output
        id: vars
        run: |
          echo "short_ref=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
          echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: 下载源码
        id: check
        uses: actions/checkout@v4

      - name: 初始化 JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: 初始化 Android SDK
        uses: android-actions/setup-android@v3

      - name: 初始化 Gradle
        uses: gradle/gradle-build-action@v3

      - name: 打包模版 APP
        run: |
          chmod 777 ./gradlew
          ./gradlew app:buildTemplateApp

      - name: 打包 Auto.js App
        run: |
          ./gradlew app:assembleV6

      - name: 对 APP 进行签名
        uses: Tlaster/android-sign@v1.2.2
        with:
          releaseDirectory: |
            app/build/outputs/apk/v6/release
          signingKeyBase64: ${{ secrets.ASIGNING_KEY }}
          alias: ${{ secrets.AALIAS }}
          keyStorePassword: ${{ secrets.AKEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.AKEY_PASSWORD }}
          output: build/app/signed
        env: 
          BUILD_TOOLS_VERSION: "34.0.0"

      - name: 重命名 apk
        run: |
          cd build/app/signed
          mv app-v6-arm64-v8a-*.apk Autox-v6-arm64-v8a-release-${{steps.vars.outputs.short_ref}}.apk
          mv app-v6-armeabi-v7a-*.apk Autox-v6-armeabi-v7a-release-${{steps.vars.outputs.short_ref}}.apk
          mv app-v6-universal-*.apk Autox-v6-universal-release-${{steps.vars.outputs.short_ref}}.apk
          ls
      # - name: 上传 APK
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: my-apks
      #     path: build/app/signed

      - name: Release
        uses: softprops/action-gh-release@v2
        # 只在推送标签时才触发
        if: startsWith(github.ref, 'refs/tags/')
        with:
          # 匹配目录下所有文件
          files: 'build/app/signed/**'
          draft: true  # 草稿
          generate_release_notes: true  # 自动生成 Release Notes
